arm_controller:
  type: effort_controllers/JointGroupPositionController
  joints:
    - arm_joint_1
    - arm_joint_2
    - arm_joint_3
    - arm_joint_4
    - arm_joint_5
  publish_rate: 50
  arm_joint_1:
    pid:
      p: 1000
      i: 0.01
      d: 0.1
  arm_joint_2:
    pid:
      p: 1000
      i: 0.01
      d: 0.1
  arm_joint_3:
    pid:
      p: 1000
      i: 0.01
      d: 0.1
  arm_joint_4:
    pid:
      p: 1000
      i: 0.01
      d: 0.1
  arm_joint_5:
    pid:
      p: 1000
      i: 0.01
      d: 0.1
