gripper_controller:
  type: effort_controllers/JointGroupPositionController
  joints:
    - gripper_finger_joint_l
    - gripper_finger_joint_r
  publish_rate: 50
  gripper_finger_joint_l:
    pid:
      p: 1000
      d: 1.0
  gripper_finger_joint_r:
    pid:
      p: 1000
      d: 1.0